import { bootstrapApplication } from '@angular/platform-browser';
import {
  RouteReuseStrategy,
  provideRouter,
  withPreloading,
  PreloadAllModules,
} from '@angular/router';
import {
  IonicRouteStrategy,
  provideIonicAngular,
} from '@ionic/angular/standalone';
import { provideHttpClient } from '@angular/common/http';
import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { addIcons } from 'ionicons';
import {
  funnelOutline,
  searchOutline,
  refreshOutline,
  personCircleOutline,
  calendarOutline,
  carOutline,
  alertCircleOutline,
  hammerOutline,
  informationCircleOutline,
  personOutline,
  personRemoveOutline,
  saveOutline,
  carSportOutline,
  documentTextOutline,
  cameraOutline,
  closeOutline,
  sendOutline,
  colorPalette,
  warning,
  receiptOutline,
  water,
  documentText,
  camera,
  close,
  checkmarkDoneCircleOutline,
  checkmarkCircleOutline,
  sync,
  syncCircleOutline,
  help,
  helpCircleOutline,
  closeCircleOutline,
  ellipseOutline,
  eye,
  eyeOutline,
  chevronDownCircleOutline,
  fileTrayOutline,
  playCircleOutline,
  chevronBack,
  chevronForward,
  createOutline,
  cameraReverseOutline,
  time,
  timeOutline,
  speedometerOutline,
  eyeOffOutline,
  fileTrayStackedOutline,
  fileTrayFullOutline,
  flagOutline,
  checkmarkDone,
  checkmarkDoneOutline,
  cardOutline,
  expandOutline,
} from 'ionicons/icons';
import { create } from 'sortablejs';

// Register Ionic icons for use in the app
addIcons({
  'funnel-outline': funnelOutline,
  'search-outline': searchOutline,
  'refresh-outline': refreshOutline,
  'person-circle-outline': personCircleOutline,
  'calendar-outline': calendarOutline,
  'car-outline': carOutline,
  'alert-circle-outline': alertCircleOutline,
  'hammer-outline': hammerOutline,
  'information-circle-outline': informationCircleOutline,
  'person-outline': personOutline,
  'person-remove-outline': personRemoveOutline,
  'save-outline': saveOutline,
  'car-sport-outline': carSportOutline,
  'document-text-outline': documentTextOutline,
  'camera-outline': cameraOutline,
  'close-outline': closeOutline,
  'send-outline': sendOutline,
  'color-palette': colorPalette,
  warning: warning,
  'receipt-outline': receiptOutline,
  water: water,
  'document-text': documentText,
  camera: camera,
  close: close,
  'checkmark-done-circle-outline': checkmarkDoneCircleOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'sync-circle-outline': syncCircleOutline,
  'help-circle-outline': helpCircleOutline,
  'close-circle-outline': closeCircleOutline,
  'ellipse-outline': ellipseOutline,
  'eye-outline': eyeOutline,
  'chevron-down-circle-outline': chevronDownCircleOutline,
  'file-tray-outline': fileTrayOutline,
  'play-circle-outline': playCircleOutline,
  'chevron-back': chevronBack,
  'chevron-forward': chevronForward,
  'speedometer-outline': speedometerOutline,
  'eye-off-outline': eyeOffOutline,
  'file-tray-full-outline': fileTrayFullOutline,
  'file-tray-stacked-outline': fileTrayStackedOutline,
  'flag-outline': flagOutline,
  flag: 'flag',
  'checkmark-done': checkmarkDone,
  'checkmark-done-outline': checkmarkDoneOutline,
  'time-outline': timeOutline,
  'create-outline': createOutline,
  'camera-reverse-outline': cameraReverseOutline,
  'card-outline': cardOutline,
  'expand-outline': expandOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(),
  ],
});
